name: Enhanced Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly security scan

# Minimal required permissions
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  enhanced-security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up security tools
      run: |
        # Install ShellCheck
        sudo apt-get update
        sudo apt-get install -y shellcheck

        # Install Trivy
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Run ShellCheck analysis
      run: |
        echo "🔍 Running ShellCheck on all shell scripts..."
        find . -name "*.sh" -type f | while read -r script; do
          echo "Checking: $script"
          shellcheck -e SC2034 -e SC1090 -e SC2155 -e SC2027 -e SC2086 "$script" || echo "⚠️  Issues found in $script"
        done

    - name: Run Trivy vulnerability scan
      run: |
        echo "🛡️ Running Trivy vulnerability scan..."
        trivy fs --severity HIGH,CRITICAL . --format sarif --output trivy-results.sarif || echo "⚠️  Trivy scan completed with warnings"

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Security summary
      run: |
        echo "✅ Enhanced security analysis completed"
        echo "📋 All security checks have been executed"
        echo "📊 Review the Security tab for detailed results"
