name: n8n-mcp Docker Deployment Testing
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Mondays

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        
    - name: Lint Script
      run: shellcheck install-test-n8n-mcp-docker.sh
      
    - name: Test Syntax
      run: bash -n install-test-n8n-mcp-docker.sh
      
    - name: Test Docker Integration
      run: |
        chmod +x install-test-n8n-mcp-docker.sh
        ./install-test-n8n-mcp-docker.sh --test-only
        
    - name: Security Scan
      run: |
        # Add security scanning tools here
        echo "Security scan placeholder"
        
  multi-platform-test:
    name: Multi-Platform Testing
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test Installation
      run: |
        chmod +x install-test-n8n-mcp-docker.sh
        ./install-test-n8n-mcp-docker.sh --dry-run
