name: Security Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Weekly security scan

# Minimal required permissions per GitHub Security Hardening docs
permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run ShellCheck analysis
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC2034 -e SC1090 -e SC2155 -e SC2027 -e SC2086
      with:
        severity: error
        format: gcc
        ignore_paths: >-
          logs
          .backup
          .security-backup
          .shellcheck-backup
          *.backup
          *.shellcheck-backup
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      continue-on-error: true
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'HIGH,CRITICAL'
        ignore-unfixed: true
        cache-dir: '${{ github.workspace }}/.cache/trivy'
        
    - name: Create empty SARIF if Trivy failed
      if: failure() || !hash('trivy-results.sarif')
      run: |
        echo "Creating empty SARIF file due to Trivy failure..."
        cat > trivy-results.sarif << 'EOF'
        {
          "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
          "version": "2.1.0",
          "runs": [
            {
              "tool": {
                "driver": {
                  "name": "Trivy",
                  "version": "0.28.0"
                }
              },
              "results": []
            }
          ]
        }
        EOF
        
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
        
    - name: Security summary
      run: |
        echo "✅ Security analysis completed"
        echo "📊 Check Security tab for detailed vulnerability reports"
        if [[ -f "trivy-results.sarif" ]]; then
          echo "📄 SARIF file created successfully"
        else
          echo "⚠️  SARIF file creation failed"
        fi
